### ISSUE TITLE
Rmd yaml header ignores "subtitle"

### ISSUE THREAD

**Issue by jangorecki** [yihui/litedown#13]
Reporting, in case that was overlooked
```yaml
---
title: nice title
subtitle: nice subtitle
author: nice author
output:
  litedown::html_format:
    meta:
      css: [default, snap]
      js: [snap]
---
```
if it is out of scope feel free to close
